### ISSUE TITLE
No longer working

### ISSUE THREAD

**Issue by fmonday** [custom-cards/home-setter#1]
On all devices/browsers, on HA v 0.108.3, home-setter seems to have stopped working. This may have happened with 0.108.0 but I'm not certain. There are no related errors. 
Installed with HACS: home-setter version 0.0.2

```
- url: /hacsfiles/home-setter/home-setter.js
  type: module
```
```
- type: custom:home-setter
  pages:
     - name: tablet
       path: lovelace/0
     - name: phone
       path: lovelace/5
```
